####################################################################
# AWS EC2 
  # AWS NAT 1
  CloudNetaPublicEC2:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0d6e6a06d11d7777d
      InstanceType: t2.micro
      KeyName: !Ref KeyName
      Tags:
        - Key: Name
          Value: CloudNeta-Public-EC2
      NetworkInterfaces:
        - DeviceIndex: 0
          SubnetId: !Ref CloudNetaPublicSN1
          GroupSet:
            - !Ref CloudNetaSecurityGroup
          AssociatePublicIpAddress: true
      UserData:
        Fn::Base64:
          !Sub |
            #!/bin/bash
            amazon-linux-extras install epel -y
            yum install httpd -y
            systemctl enable --now httpd
            echo "<h1>Test Web Server</h1>" > /var/www/html/index.html

# 상파울루 용 기본 linux 이미지
# ami-0d2b872bd98d125e5

# 아래는 NAT 설정된 AMI 이미지 파일 사용한 인스턴스

# 상파울루 용 NAT linux 이미지
# ami-09cb25eec461870b7

####################################################################
# AWS EC2
  Instance2:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0c2d3e23e757b5d84
      InstanceType: t2.micro
      KeyName: !Ref KeyName
      SourceDestCheck: False
      Tags:
        - Key: Name
          Value: NAT-Instance2
      NetworkInterfaces:
        - DeviceIndex: 0
          NetworkInterfaceId: !Ref InstanceENI2
      UserData:
        Fn::Base64: |
          #!/bin/bash
          hostname NAT-Instance
          yum -y install tcpdump iptraf

